export const projects = [
  { id:1,
    name:"Start Creation &co" ,
    slug:"startco",
    headerImage: "./assets/images/SCBlob.png",
    accent: "#F2994A",
    platform: "Web, responsive",
    technology: ["React","Gatsby","GraphCMS"],
    image: "./assets/images/startcreation.png",
    description: "Start Creation is coworking space that needed a little push to get new residents to work with them",
    challenges: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    gallery: [
      {src: "./assets/images/SCContact.png"},
      {src: "./assets/images/SCEvents.png"},
      {src: "./assets/images/SCHeader.png"},
      {src: "./assets/images/SCPartners.png"},
    ]
  },
  /*  { name:"Samapass" , image: "./assets/images/samapass.png" },*/
  { id:2,
    name:"Buddy Belgium" ,
    slug:"buddy-belgium",
    platform: "Web, responsive",
    technology: "React,Gatsby,GraphCMS",
    image: "./assets/images/buddybelgium.png",
    headerImage: "./assets/images/SCBlob.png",
    accent: "#4a9bf2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    challenges: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    gallery: [
      {src: "./assets/images/SCContact.png"},
      {src: "./assets/images/SCEvents.png"},
      {src: "./assets/images/SCHeader.png"},
      {src: "./assets/images/SCPartners.png"},
    ]
  },
  { id:3,
    name:"Cercle D'histoire D'Auderghem",
    slug:"chauderghem",
    platform: "Web, responsive",
    technology: "React,Gatsby,GraphCMS",
    image: "./assets/images/chauderghem.png",
    headerImage: "./assets/images/SCBlob.png",
    accent: "#7e2626",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    challenges: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    gallery: [
      {src: "./assets/images/SCContact.png"},
      {src: "./assets/images/SCEvents.png"},
      {src: "./assets/images/SCHeader.png"},
      {src: "./assets/images/SCPartners.png"},
    ]
  },

]
